# Generated by Django 4.2.5 on 2023-09-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('pmid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('keywords', models.TextField()),
                ('full_text_link', models.URLField()),
            ],
        ),
    ]
